#!/usr/bin/env python3
"""Generate consistent localized market intelligence tool pages."""

import html
import logging
from pathlib import Path
from typing import Final

ROOT: Final[Path] = Path(__file__).parent.parent
LOGGER: Final[logging.Logger] = logging.getLogger("build_market_tools")
LANGUAGES: Final[dict[str, dict[str, str]]] = {
    "": {"lang":"zh-CN","title":"黄金市场智能工具","lead":"把机构持仓、宏观驱动、风险计算和回测报告放在同一个工作台。","market":"市场数据","tools":"风险工具","lab":"回测实验室","home":"首页","news":"新闻","position":"COMEX 黄金机构持仓","drivers":"黄金驱动仪表盘","risk":"XAUUSD 仓位与风险计算","report":"MT5 回测报告分析","oi":"未平仓量","managed":"管理基金净持仓","change":"较上次抓取变化","producer":"生产商净持仓","date":"报告日期","xau":"黄金现价","dxy":"美元指数 DXY","us2":"美国 2 年期","us10":"美国 10 年期","real10":"美国 10 年实际利率","updated":"页面数据更新时间","balance":"账户余额 (USD)","riskp":"单笔风险 (%)","entry":"入场价","stop":"止损价","target":"目标价","calc":"计算仓位","amount":"风险金额","lots":"建议手数","rr":"盈亏比","upload":"选择 MT5 HTML 报告（仅本机解析）","profit":"总净利润","factor":"盈利因子","drawdown":"最大回撤","trades":"总交易数","input":"请输入有效且不相同的正数价格。","file":"报告无效或超过 10MB。","load":"市场数据暂时不可用。","source":"官方来源与频率：CFTC 每周；美国财政部收益率为每日收盘数据。"},
    "zh-tw": {"lang":"zh-TW","title":"黃金市場智慧工具","lead":"把機構持倉、宏觀驅動、風險計算和回測報告放在同一個工作台。","market":"市場數據","tools":"風險工具","lab":"回測實驗室","home":"首頁","news":"新聞","position":"COMEX 黃金機構持倉","drivers":"黃金驅動儀表板","risk":"XAUUSD 倉位與風險計算","report":"MT5 回測報告分析","oi":"未平倉量","managed":"管理基金淨持倉","change":"較上次抓取變化","producer":"生產商淨持倉","date":"報告日期","xau":"黃金現價","dxy":"美元指數 DXY","us2":"美國 2 年期","us10":"美國 10 年期","real10":"美國 10 年實際利率","updated":"頁面數據更新時間","balance":"帳戶餘額 (USD)","riskp":"單筆風險 (%)","entry":"入場價","stop":"止損價","target":"目標價","calc":"計算倉位","amount":"風險金額","lots":"建議手數","rr":"盈虧比","upload":"選擇 MT5 HTML 報告（僅本機解析）","profit":"總淨利潤","factor":"盈利因子","drawdown":"最大回撤","trades":"總交易數","input":"請輸入有效且不相同的正數價格。","file":"報告無效或超過 10MB。","load":"市場數據暫時不可用。","source":"官方來源與頻率：CFTC 每週；美國財政部收益率為每日收盤數據。"},
    "en": {"lang":"en","title":"Gold Market Intelligence Tools","lead":"Institutional positioning, macro drivers, risk sizing and MT5 report analysis in one workspace.","market":"Markets","tools":"Risk tools","lab":"Backtest lab","home":"Home","news":"News","position":"COMEX Gold Institutional Positioning","drivers":"Gold Drivers Dashboard","risk":"XAUUSD Position & Risk Calculator","report":"MT5 Backtest Report Analyzer","oi":"Open interest","managed":"Managed money net","change":"Change since prior fetch","producer":"Producer net","date":"Report date","xau":"Gold spot","dxy":"US Dollar Index DXY","us2":"US 2-year","us10":"US 10-year","real10":"US 10-year real yield","updated":"Page data updated","balance":"Account balance (USD)","riskp":"Risk per trade (%)","entry":"Entry price","stop":"Stop price","target":"Target price","calc":"Calculate size","amount":"Risk amount","lots":"Suggested lots","rr":"Reward / risk","upload":"Choose an MT5 HTML report (parsed locally)","profit":"Total net profit","factor":"Profit factor","drawdown":"Max drawdown","trades":"Total trades","input":"Enter valid positive prices with a different stop.","file":"The report is invalid or exceeds 10MB.","load":"Market data is temporarily unavailable.","source":"Official sources and cadence: CFTC weekly; US Treasury yields are daily closes."},
    "ja": {"lang":"ja","title":"ゴールド市場インテリジェンス","lead":"機関投資家ポジション、マクロ要因、リスク計算、MT5レポート分析を一つに。","market":"市場","tools":"リスクツール","lab":"バックテスト","home":"ホーム","news":"ニュース","position":"COMEX 金の機関投資家ポジション","drivers":"金価格ドライバー","risk":"XAUUSD ポジション計算","report":"MT5 レポート分析","oi":"未決済建玉","managed":"マネージドマネー純ポジション","change":"前回取得比","producer":"生産者純ポジション","date":"報告日","xau":"金現物","dxy":"米ドル指数 DXY","us2":"米国2年債","us10":"米国10年債","real10":"米国10年実質金利","updated":"データ更新時刻","balance":"口座残高 (USD)","riskp":"1取引リスク (%)","entry":"エントリー","stop":"ストップ","target":"目標価格","calc":"計算","amount":"リスク金額","lots":"推奨ロット","rr":"損益比","upload":"MT5 HTMLレポートを選択（ローカル解析）","profit":"純利益","factor":"プロフィットファクター","drawdown":"最大ドローダウン","trades":"総取引数","input":"有効な正数を入力してください。","file":"レポートが無効か10MBを超えています。","load":"市場データを利用できません。","source":"公式情報：CFTCは週次、米財務省利回りは日次終値。"},
    "ko": {"lang":"ko","title":"금 시장 인텔리전스 도구","lead":"기관 포지션, 거시 동인, 위험 계산과 MT5 보고서 분석을 한곳에서 제공합니다.","market":"시장","tools":"위험 도구","lab":"백테스트","home":"홈","news":"뉴스","position":"COMEX 금 기관 포지션","drivers":"금 가격 동인 대시보드","risk":"XAUUSD 포지션 및 위험 계산","report":"MT5 백테스트 보고서 분석","oi":"미결제약정","managed":"관리자금 순포지션","change":"이전 수집 대비","producer":"생산자 순포지션","date":"보고일","xau":"금 현물","dxy":"달러 인덱스 DXY","us2":"미국 2년물","us10":"미국 10년물","real10":"미국 10년 실질금리","updated":"데이터 업데이트","balance":"계좌 잔액 (USD)","riskp":"거래당 위험 (%)","entry":"진입가","stop":"손절가","target":"목표가","calc":"포지션 계산","amount":"위험 금액","lots":"권장 랏","rr":"손익비","upload":"MT5 HTML 보고서 선택 (로컬 분석)","profit":"총 순이익","factor":"수익 계수","drawdown":"최대 낙폭","trades":"총 거래","input":"유효한 양수 가격을 입력하세요.","file":"보고서가 잘못되었거나 10MB를 초과합니다.","load":"시장 데이터를 사용할 수 없습니다.","source":"공식 출처: CFTC 주간, 미국 재무부 수익률 일일 종가."},
    "de": {"lang":"de","title":"Goldmarkt-Intelligenztools","lead":"Institutionelle Positionierung, Makrotreiber, Risikoberechnung und MT5-Berichtsanalyse an einem Ort.","market":"Märkte","tools":"Risikotools","lab":"Backtest-Labor","home":"Start","news":"Nachrichten","position":"Institutionelle COMEX-Goldpositionen","drivers":"Goldtreiber-Dashboard","risk":"XAUUSD Positions- und Risikorechner","report":"MT5 Backtest-Berichtsanalyse","oi":"Offenes Interesse","managed":"Managed-Money netto","change":"Änderung seit letztem Abruf","producer":"Produzenten netto","date":"Berichtsdatum","xau":"Gold Spot","dxy":"US-Dollar-Index DXY","us2":"US 2 Jahre","us10":"US 10 Jahre","real10":"US 10J Realzins","updated":"Daten aktualisiert","balance":"Kontostand (USD)","riskp":"Risiko je Trade (%)","entry":"Einstieg","stop":"Stop","target":"Ziel","calc":"Größe berechnen","amount":"Risikobetrag","lots":"Empfohlene Lots","rr":"Chance/Risiko","upload":"MT5-HTML-Bericht wählen (lokale Analyse)","profit":"Nettogewinn","factor":"Profitfaktor","drawdown":"Max. Drawdown","trades":"Trades gesamt","input":"Gültige positive Preise eingeben.","file":"Bericht ungültig oder größer als 10 MB.","load":"Marktdaten vorübergehend nicht verfügbar.","source":"Offizielle Quellen: CFTC wöchentlich; US-Treasury-Renditen täglicher Schlussstand."},
    "fr": {"lang":"fr","title":"Outils d’intelligence du marché de l’or","lead":"Positions institutionnelles, moteurs macro, calcul du risque et analyse des rapports MT5 au même endroit.","market":"Marchés","tools":"Risque","lab":"Laboratoire","home":"Accueil","news":"Actualités","position":"Positions institutionnelles COMEX Or","drivers":"Tableau des moteurs de l’or","risk":"Calculateur de position et risque XAUUSD","report":"Analyse de rapport MT5","oi":"Intérêt ouvert","managed":"Managed money net","change":"Écart depuis la collecte précédente","producer":"Producteurs net","date":"Date du rapport","xau":"Or spot","dxy":"Indice dollar DXY","us2":"Taux US 2 ans","us10":"Taux US 10 ans","real10":"Taux réel US 10 ans","updated":"Données mises à jour","balance":"Solde du compte (USD)","riskp":"Risque par trade (%)","entry":"Entrée","stop":"Stop","target":"Objectif","calc":"Calculer la taille","amount":"Montant risqué","lots":"Lots suggérés","rr":"Rendement / risque","upload":"Choisir un rapport HTML MT5 (analyse locale)","profit":"Profit net","factor":"Facteur de profit","drawdown":"Drawdown max.","trades":"Total des trades","input":"Saisissez des prix positifs valides.","file":"Rapport invalide ou supérieur à 10 Mo.","load":"Données de marché indisponibles.","source":"Sources officielles : CFTC hebdomadaire ; taux du Trésor américain en clôture quotidienne."},
}


def page(t: dict[str, str], prefix: str) -> str:
    canonical = f"https://03xau.com/{prefix + '/' if prefix else ''}market-tools.html"
    home = f"/{prefix + '/' if prefix else ''}"
    news = f"/{prefix + '/' if prefix else ''}news.html"
    alternates = "\n".join(
        f'<link rel="alternate" hreflang="{v["lang"]}" href="https://03xau.com/{k + "/" if k else ""}market-tools.html">'
        for k, v in LANGUAGES.items()
    )
    alternates += '\n<link rel="alternate" hreflang="x-default" href="https://03xau.com/en/market-tools.html">'
    value_cards = lambda items: "".join(f'<article class="mt-card"><span class="mt-label">{html.escape(label)}</span><strong class="mt-value" id="{node}" data-market-value>—</strong></article>' for label,node in items)
    return f'''<!doctype html><html lang="{t["lang"]}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#080b10"><title>{t["title"]} | XAU Quant</title><meta name="description" content="{t["lead"]}"><meta name="robots" content="index,follow"><link rel="canonical" href="{canonical}">{alternates}<link rel="stylesheet" href="/assets/market-tools.css"><link rel="icon" href="/favicon.svg"></head>
<body data-input-error="{t["input"]}" data-file-error="{t["file"]}" data-load-error="{t["load"]}"><nav class="mt-nav"><div class="mt-wrap mt-nav-inner"><a class="mt-brand" href="{home}">XAU QUANT</a><div class="mt-links"><a href="{home}">{t["home"]}</a><a aria-current="page" href="#markets">{t["market"]}</a><a href="#risk">{t["tools"]}</a><a href="#lab">{t["lab"]}</a><a href="{news}">{t["news"]}</a></div></div></nav>
<header class="mt-wrap mt-hero"><span class="mt-kicker">XAU INTELLIGENCE</span><h1>{t["title"]}</h1><p>{t["lead"]}</p></header>
<main><section class="mt-wrap mt-section" id="markets"><div class="mt-section-head"><h2>{t["position"]}</h2><span class="mt-source">{t["source"]}</span></div><div class="mt-grid">{value_cards([(t["managed"],"cot-managed"),(t["change"],"cot-change"),(t["producer"],"cot-producer"),(t["oi"],"cot-oi"),(t["date"],"cot-date")])}</div></section>
<section class="mt-wrap mt-section"><div class="mt-section-head"><h2>{t["drivers"]}</h2><span class="mt-source" id="market-status"></span></div><div class="mt-grid">{value_cards([(t["xau"],"driver-xau"),(t["dxy"],"driver-dxy"),(t["us2"],"driver-us2y"),(t["us10"],"driver-us10y"),(t["real10"],"driver-real10"),(t["updated"],"driver-time")])}</div></section>
<section class="mt-wrap mt-section" id="risk"><div class="mt-section-head"><h2>{t["risk"]}</h2></div><div class="mt-card"><div class="mt-form">{fields(t)}</div><button class="mt-button" id="risk-calculate" type="button">{t["calc"]}</button><span class="mt-sub" id="risk-message"></span><div class="mt-grid mt-results">{value_cards([(t["amount"],"risk-amount"),(t["lots"],"risk-lots"),(t["rr"],"risk-rr")])}</div></div></section>
<section class="mt-wrap mt-section" id="lab"><div class="mt-section-head"><h2>{t["report"]}</h2></div><div class="mt-card"><label class="mt-label" for="report-file">{t["upload"]}</label><input class="mt-upload" id="report-file" type="file" accept=".html,.htm,text/html"><span class="mt-sub" id="report-status"></span><div class="mt-grid mt-results">{value_cards([(t["profit"],"report-profit"),(t["factor"],"report-factor"),(t["drawdown"],"report-drawdown"),(t["trades"],"report-trades")])}</div></div></section></main>
<footer class="mt-footer"><div class="mt-wrap">© XAU Quant · CFTC / U.S. Treasury official public data · Not investment advice.</div></footer><script src="/assets/market-tools.js" defer></script></body></html>'''


def fields(t: dict[str, str]) -> str:
    specs = [("risk-balance",t["balance"],"10000"),("risk-percent",t["riskp"],"1"),("risk-entry",t["entry"],"2400"),("risk-stop",t["stop"],"2390"),("risk-target",t["target"],"2420")]
    return "".join(f'<div class="mt-field"><label for="{node}">{label}</label><input id="{node}" type="number" inputmode="decimal" min="0" step="any" value="{value}"></div>' for node,label,value in specs)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")
    for prefix, translations in LANGUAGES.items():
        directory = ROOT / prefix if prefix else ROOT
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "market-tools.html").write_text(page(translations, prefix), encoding="utf-8")
    LOGGER.info("Localized market tool pages generated", extra={"count": len(LANGUAGES)})


if __name__ == "__main__":
    main()
